# Generated by Django 6.0.2 on 2026-03-09 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_comment_id_alter_post_id_alter_post_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-date_creation"]},
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="body",
            new_name="contenu",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="created_on",
            new_name="date_creation",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="content",
            new_name="contenu",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="created_on",
            new_name="date_creation",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="active",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="email",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="name",
        ),
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.RemoveField(
            model_name="post",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="post",
            name="title",
        ),
        migrations.RemoveField(
            model_name="post",
            name="updated_on",
        ),
        migrations.AddField(
            model_name="comment",
            name="actif",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="auteur",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="auteur",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="titre",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Brouillon"), (1, "Publié")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("etudiant", "Étudiant"), ("alumni", "Alumni")], max_length=20
            ),
        ),
    ]
